version: 2.1

orbs:
  node: circleci/node@5.2.0
  docker: circleci/docker@1.4.0

jobs:
  deloy:
    executor: docker/docker
    steps:
       - add_ssh_keys:
          fingerprints:
            - "ce:8d:9e:16:9c:cc:68:11:38:20:c9:7e:68:34:02:02"
       - run: ssh -p  5999  -o StrictHostKeyChecking=no -v test@125.212.250.1 './deloy_linh.sh'
workflows:
  commit:
    jobs:
      - deloy:
          filters:
            branches:
              only:
                - main
    
