version: 2.1

orbs:
  node: circleci/node@5.2.0
  docker: circleci/docker@1.4.0

jobs:
  deloy:
    executor: docker/docker
    steps:
       - run: ssh -p  5999 -v test@125.212.250.1 './deloy_linh.sh'
workflows:
  commit:
    jobs:
       - node/test

