version: 2.1

orbs:
  node: circleci/node@5.2.0
  docker: circleci/docker@1.4.0

jobs:
  deloy:
    executor: docker/docker
    steps:
      #  - add_ssh_keys:
      #     fingerprints:
      #       - "0b:f1:3d:fa:47:3b:ab:90:ad:89:25:d2:0a:36:5b:eb"
      #  - checkout
       - run: - run: ls -a
workflows:
  commit:
    jobs:
      - deloy:
          filters:
            branches:
              only:
                - main
    
